### ISSUE TITLE
Partition changes...maybe...

### ISSUE THREAD

**Issue by modrobert** [dennisMe2/usbfd#3]
First off, thanks for a great script, helped me a lot with the Gotek.

I just wanted to mention that the device partitioning seems to be slightly different in my Gotek, perhaps different firmware version. I used the internal USB format function by pressing both buttons on the Gotek during power on, not sure if the 'usbfd' format will work, haven't tried it.

The device to use in my Linux is /dev/sdx1, when using /dev/sdx it fails (where 'x' marks the device letter). The "mount" and "unmount" commands in 'usbfd' works with that device.

**Comment by dennisMe2** [comment]
Which Linux are you using?

**Comment by modrobert** [comment]
Linux kernel 3.19.0-15.

After checking another Kingston USB flash stick, it seems they come partitioned from factory with a small unallocated part. At first I thought that the Gotek internal format did that, but later read in the manual that the flash stick needs to be formatted FAT16/32 before doing this, so the reason for /dev/sdb1 in my case is probably due to the partitioning on the USB stick before doing the "Gotek format".

**Comment by dennisMe2** [comment]
Thanks!
