### ISSUE TITLE
USBFD and 008 volume

### ISSUE THREAD

**Issue by biuro74** [dennisMe2/usbfd#4]
Hello,

I've just formatted all 100 volumes:
./usbfd -fd /dev/sdc {0..99}
(it was a message telling me there's something wrong with 032 volume, probably "root" volume (000) has been treated as 032), but it's not an issue... yet ;-) It's a command message:

Volume ID is 8ba7d361, volume label FDISK000   .
Volume ID is 8ba9e28d, volume label FDISK001   .
Volume ID is 8bb13170, volume label FDISK002   .
Volume ID is 8bb1b900, volume label FDISK003   .
Volume ID is 8bc63ddf, volume label FDISK004   .
Volume ID is 8bca188c, volume label FDISK005   .
Volume ID is 8bca3130, volume label FDISK006   .
Volume ID is 8bca473f, volume label FDISK007   .
Volume ID is 8bca650b, volume label FDISK008   .
Volume ID is 8bca7c02, volume label FDISK009   .
Volume ID is 8bca94e5, volume label FDISK010   .
Volume ID is 8bcaa4e3, volume label FDISK011   .
Volume ID is 8bcab7de, volume label FDISK012   .
Volume ID is 8bcac9ac, volume label FDISK013   .
Volume ID is 8bcad938, volume label FDISK014   .
Volume ID is 8bcaec78, volume label FDISK015   .
Volume ID is 8bcafca4, volume label FDISK016   .
Volume ID is 8bcb12cc, volume label FDISK017   .
Volume ID is 8bcb2536, volume label FDISK018   .
Volume ID is 8bcb3757, volume label FDISK019   .
Volume ID is 8bcb4678, volume label FDISK020   .
Volume ID is 8bcb568f, volume label FDISK021   .
Volume ID is 8bcb67fc, volume label FDISK022   .
Volume ID is 8bcb7785, volume label FDISK023   .
Volume ID is 8bcb8a14, volume label FDISK024   .
Volume ID is 8bcb98a8, volume label FDISK025   .
Volume ID is 8bcba5e0, volume label FDISK026   .
Volume ID is 8bcbb576, volume label FDISK027   .
Volume ID is 8bcbc234, volume label FDISK028   .
Volume ID is 8bcbd487, volume label FDISK029   .
Volume ID is 8bcbe48b, volume label FDISK030   .
Volume ID is 8bcbf094, volume label FDISK031   .
usbfd032 is already mounted, try -u first
Volume ID is 8bcbff87, volume label FDISK033   .
Volume ID is 8bcc6d93, volume label FDISK034   .
Volume ID is 8bccd52f, volume label FDISK035   .
Volume ID is 8bcd3d44, volume label FDISK036   .
Volume ID is 8bcda786, volume label FDISK037   .
Volume ID is 8bce0eae, volume label FDISK038   .
Volume ID is 8bce751d, volume label FDISK039   .
Volume ID is 8bcedf49, volume label FDISK040   .
Volume ID is 8bd005b5, volume label FDISK041   .
Volume ID is 8bd06dfc, volume label FDISK042   .
Volume ID is 8bd0d59c, volume label FDISK043   .
Volume ID is 8bd13f24, volume label FDISK044   .
Volume ID is 8bd1a7e0, volume label FDISK045   .
Volume ID is 8bd2132b, volume label FDISK046   .
Volume ID is 8bd27a9f, volume label FDISK047   .
Volume ID is 8bd2e0c9, volume label FDISK048   .
Volume ID is 8bd35085, volume label FDISK049   .
Volume ID is 8bd3bb76, volume label FDISK050   .
Volume ID is 8bd42089, volume label FDISK051   .
Volume ID is 8bd4885f, volume label FDISK052   .
Volume ID is 8bd4ef70, volume label FDISK053   .
Volume ID is 8bd5575e, volume label FDISK054   .
Volume ID is 8bd5be84, volume label FDISK055   .
Volume ID is 8bd62565, volume label FDISK056   .
Volume ID is 8bd68c9f, volume label FDISK057   .
Volume ID is 8bd6f378, volume label FDISK058   .
Volume ID is 8bd75c52, volume label FDISK059   .
Volume ID is 8bd7c59f, volume label FDISK060   .
Volume ID is 8bd829d9, volume label FDISK061   .
Volume ID is 8bd88f76, volume label FDISK062   .
Volume ID is 8bd8f5c7, volume label FDISK063   .
Volume ID is 8bd96032, volume label FDISK064   .
Volume ID is 8bd9c7e3, volume label FDISK065   .
Volume ID is 8bda2e01, volume label FDISK066   .
Volume ID is 8bda938d, volume label FDISK067   .
Volume ID is 8bdafb91, volume label FDISK068   .
Volume ID is 8bdb6218, volume label FDISK069   .
Volume ID is 8bdbc64e, volume label FDISK070   .
Volume ID is 8bdc2e4e, volume label FDISK071   .
Volume ID is 8bdc9131, volume label FDISK072   .
Volume ID is 8bdcfa7d, volume label FDISK073   .
Volume ID is 8bdd5fb4, volume label FDISK074   .
Volume ID is 8bddc367, volume label FDISK075   .
Volume ID is 8bde2958, volume label FDISK076   .
Volume ID is 8bde9221, volume label FDISK077   .
Volume ID is 8bdef61b, volume label FDISK078   .
Volume ID is 8be01e14, volume label FDISK079   .
Volume ID is 8be07fd9, volume label FDISK080   .
Volume ID is 8be0e52a, volume label FDISK081   .
Volume ID is 8be14d00, volume label FDISK082   .
Volume ID is 8be1b6d1, volume label FDISK083   .
Volume ID is 8be21b57, volume label FDISK084   .
Volume ID is 8be28217, volume label FDISK085   .
Volume ID is 8be2ea43, volume label FDISK086   .
Volume ID is 8be351f5, volume label FDISK087   .
Volume ID is 8be3c061, volume label FDISK088   .
Volume ID is 8be42434, volume label FDISK089   .
Volume ID is 8be487e6, volume label FDISK090   .
Volume ID is 8be4f137, volume label FDISK091   .
Volume ID is 8be55897, volume label FDISK092   .
Volume ID is 8be5be9d, volume label FDISK093   .
Volume ID is 8be620b7, volume label FDISK094   .
Volume ID is 8be68849, volume label FDISK095   .
Volume ID is 8be6f286, volume label FDISK096   .
Volume ID is 8be75ac8, volume label FDISK097   .
Volume ID is 8be7bfac, volume label FDISK098   .
Volume ID is 8be825f9, volume label FDISK099   .

Then I've mounted first four of them
./usbfd -md /dev/sdc {0..3}
and it was fine: FDISK000, FDISK001, FDISK002, FDISK003.

And then, I've tried to mount volume 010 (FDISK010) 
./usbfd -md /dev/sdc 010
and it seems like it mounts 008 drive (FDISK008)

So I've dismounted all and tried to mount volume 008
./usbfd -md /dev/sdc 008

and I get error message (transcription):
./usbfd: line 108: printf: 008: incorrect octal value
./usbfd: line 115: let: MYOFFSET=1572864*008: value too big for a base (incorrect "008" tag)
mount: couldn't analyze mount options

Help, please :)
Yes, I know I can mount it via ./usbfd -md /dev/sdc 8, but in the future I will probably forget it and will be nervous why it doesn't work :)

**Comment by dennisMe2** [comment]
Darn it, Bash is interpreting drive 010 as octal (008)...
I'll fix it ASAP, hopefully tonight.
If you're really in a hurry you could try this:
http://ubuntuforums.org/showthread.php?t=1402291

Basically the variable $FLOP needs to be prefixed with 10# to indicate it is a decimal number. (prefixing with 0 generally indicates an octal number).

**Comment by jsanpedro** [comment]
one idea is to use the old-ish syntax `expr $var1 \* $var2` which interprets all numbers as decimal

**Comment by dennisMe2** [comment]
Fixed by prefixing certain numbers with "10#" to force bash to interpret the numbers as decimal. Phew, that took me a long time, didn't it!
